import { memberFromRequest, optionsOk, jsonOk, jsonErr } from "@/lib/apiAuth";
import {
  billableSummary,
  exportTimesheetCsv,
  addOfflineTime,
  timesheetRows,
  listClients,
} from "@/lib/backlog";
import { NextResponse } from "next/server";
import { corsHeaders } from "@/lib/apiAuth";

const esc = (s: string) =>
  String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c] || c));
const money = (cents: number, cur = "EUR") =>
  new Intl.NumberFormat("en-GB", { style: "currency", currency: cur }).format(cents / 100);

/** E5-S5 — Invoice-ready HTML that prints straight to PDF (no external lib). */
function invoiceHtml(memberName: string, clientName: string, ts: ReturnType<typeof timesheetRows>) {
  const cur = ts.lines[0]?.currency || "EUR";
  const rows = ts.lines
    .map(
      (l) => `<tr>
        <td>${esc(l.date)}</td>
        <td>${esc(l.project || "—")}</td>
        <td class="n">${(l.minutes / 60).toFixed(2)}</td>
        <td class="n">${money(l.rate_cents, l.currency)}</td>
        <td class="n">${money(l.amount_cents, l.currency)}</td>
      </tr>`
    )
    .join("");
  return `<!doctype html><html><head><meta charset="utf-8"><title>Invoice ${esc(clientName)} ${esc(ts.from)}–${esc(ts.to)}</title>
<style>
  *{box-sizing:border-box}
  body{font:14px/1.5 -apple-system,system-ui,"Segoe UI",Roboto,sans-serif;color:#1a1c20;max-width:760px;margin:32px auto;padding:0 24px}
  header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #c4653a;padding-bottom:16px}
  h1{font-size:26px;margin:0;color:#c4653a;letter-spacing:-.01em}
  .meta{text-align:right;color:#555;font-size:13px}
  .parties{display:flex;gap:48px;margin:24px 0}
  .parties h3{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#888;margin:0 0 4px}
  table{width:100%;border-collapse:collapse;margin-top:12px}
  th{text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:#888;border-bottom:1px solid #ddd;padding:8px 6px}
  td{padding:8px 6px;border-bottom:1px solid #f0f0f0}
  td.n,th.n{text-align:right;font-variant-numeric:tabular-nums}
  th.n{text-align:right}
  tfoot td{border-top:2px solid #1a1c20;border-bottom:none;font-weight:700;font-size:16px;padding-top:12px}
  .hint{color:#999;font-size:12px;margin-top:32px}
  @media print{.hint{display:none}body{margin:0}}
</style></head><body onload="window.print()">
  <header>
    <div><h1>Invoice</h1><div style="color:#666;margin-top:4px">${esc(ts.from)} → ${esc(ts.to)}</div></div>
    <div class="meta">Total hours: <b>${(ts.total_minutes / 60).toFixed(2)}</b></div>
  </header>
  <div class="parties">
    <div><h3>From</h3>${esc(memberName)}</div>
    <div><h3>Bill to</h3>${esc(clientName || "All clients")}</div>
  </div>
  <table>
    <thead><tr><th>Date</th><th>Project</th><th class="n">Hours</th><th class="n">Rate</th><th class="n">Amount</th></tr></thead>
    <tbody>${rows || `<tr><td colspan="5" style="color:#999;text-align:center;padding:24px">No billable sessions in this period.</td></tr>`}</tbody>
    <tfoot><tr><td colspan="4">Total</td><td class="n">${money(ts.total_cents, cur)}</td></tr></tfoot>
  </table>
  <p class="hint">Generated by Fellowship Focus · use your browser's “Save as PDF”. Totals reconcile to the CSV export.</p>
</body></html>`;
}

export async function OPTIONS() {
  return optionsOk();
}

export async function GET(request: Request) {
  const member = await memberFromRequest(request);
  if (!member) return jsonErr("Token required", 401);
  const url = new URL(request.url);
  const to = url.searchParams.get("to") || new Date().toISOString().slice(0, 10);
  const from =
    url.searchParams.get("from") ||
    new Date(Date.now() - 7 * 86400000).toISOString().slice(0, 10);
  const clientId = url.searchParams.get("client_id") || undefined;
  const format = url.searchParams.get("format");
  if (format === "csv") {
    const csv = exportTimesheetCsv(member.id, from, to, clientId);
    return new NextResponse(csv, {
      headers: {
        ...corsHeaders,
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="timesheet-${from}-${to}.csv"`,
      },
    });
  }
  if (format === "invoice") {
    const ts = timesheetRows(member.id, from, to, clientId);
    const clientName = clientId
      ? listClients(member.id).find((c) => c.id === clientId)?.name || ""
      : "";
    return new NextResponse(invoiceHtml(member.name, clientName, ts), {
      headers: { ...corsHeaders, "Content-Type": "text/html; charset=utf-8" },
    });
  }
  return jsonOk(billableSummary(member.id, from, to));
}

export async function POST(request: Request) {
  const member = await memberFromRequest(request);
  if (!member) return jsonErr("Token required", 401);
  const body = await request.json();
  if (!body.date || !body.minutes) return jsonErr("date and minutes required", 400);
  return jsonOk(addOfflineTime(member.id, body), 201);
}
